### PR TITLE
Add NestedHV config option for vsphere-iso builder

### LINKED ISSUE #67: Support for NestedHV for iso builder
Would like support for the NestedHV VM build option (for running 1709 Windows on vSphere to support the Hyper-V role).

### PR DESCRIPTION
**Pull request by seanmalloy**
Fixes #67

### CODE REVIEW

**Comment by seanmalloy** [comment]
I verified that this is working in my environment(vCetner 6.0). I still need to create tests for this code change before this can be merged.

**Comment by seanmalloy** [comment]
@mkuzmin I added the unit tests, but did not run them in my environment. Let me know if any changes are needed.

**Comment by casey-robertson** [comment]
@seanmalloy how should I go about building this extension?  Struggled a bit before.  Would love to test it out so I can automate my Windows docker host running in VMWare.

**Comment by casey-robertson** [comment]
``bash-3.2$ ./build.sh
+ dep ensure
+ export CGO_ENABLED=0
+ CGO_ENABLED=0
+ export GOARCH=amd64
+ GOARCH=amd64
+ mkdir -p bin
+ rm -f 'bin/*'
+ GOOS=darwin
+ go build -o bin/packer-builder-vsphere-iso.macos ./cmd/iso
# _/Users/casey.robertson/go/src/github.com/KohlsTechnology/packer-builder-vsphere/cmd/iso
cmd/iso/main.go:11:28: cannot use new(iso.Builder) (type *iso.Builder) as type "github.com/hashicorp/packer/packer".Builder in argument to server.RegisterBuilder:
	*iso.Builder does not implement "github.com/hashicorp/packer/packer".Builder (wrong type for Run method)
		have Run("github.com/jetbrains-infra/packer-builder-vsphere/vendor/github.com/hashicorp/packer/packer".Ui, "github.com/jetbrains-infra/packer-builder-vsphere/vendor/github.com/hashicorp/packer/packer".Hook, "github.com/jetbrains-infra/packer-builder-vsphere/vendor/github.com/hashicorp/packer/packer".Cache) ("github.com/jetbrains-infra/packer-builder-vsphere/vendor/github.com/hashicorp/packer/packer".Artifact, error)
		want Run("github.com/hashicorp/packer/packer".Ui, "github.com/hashicorp/packer/packer".Hook, "github.com/hashicorp/packer/packer".Cache) ("github.com/hashicorp/packer/packer".Artifact, error)``

**Comment by seanmalloy** [comment]
@casey-robertson it compiles fine on my machine. I'm running on Fedora 27 with Go version 1.10 with dep version 0.4.1. All I'm doing is running `./builds.sh` from this repo. Are you able to compile the code from the master branch? It would probably be best if you open up a separate issue if you are not able to compile from master.

I compiled all of the binaries for you using the code on this branch. You can download them from the below URL.

https://storage.cloud.google.com/smalloy-sbx1-public/packer-issue-67.tar.gz

**Comment by mkuzmin** [comment]
@casey-robertson use `docker-compose run build`

@seanmalloy I'm back from a vacation, and now reviewing all the PRs and docs changes. Thank you!
